title: STEM @ Mountlake Terrace
author: Jakob Nacanaynay
keywords: stem, mths, mountlake, terrace, science, technology, somputer science, aerospace, biotechnology
email: jnac8080@gmail.com
description: >-
  See what students are making in the STEM program at Mountlake Terrace High School
baseurl: "/solid" # the subpath of your site, e.g. /blog
url: "https://hawks-who-code.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Hawks-Who-Code

plugins:
  - jekyll-feed
